export const CHANGE_THEME = "CHANGE_THEME";
export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
