export const CHANGE_THEME = "CHANGE_THEME";

export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCH_FORECAST_REQUEST = "FETCH_FORECAST_REQUEST";
export const FETCH_FORECAST_FAILURE = "FETCH_FORECAST_FAILURE";
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";